### ISSUE TITLE
Report form — category and description fields

### ISSUE THREAD

**Issue by musaalamparvez** [musaalamparvez/hse-near-miss-reporting#6]
## Goal

The report form (from #5) gains a category selector and a description field.

## Acceptance criteria

- [ ] Form shows a `category` dropdown with exactly: Slip/Trip/Fall, Equipment, Chemical, Electrical, Other — matching `Report.Category` in `core/models.py`.
- [ ] Selecting "Other" reveals a free-text detail field (maps to `category_other_detail`); the field stays hidden for every other category.
- [ ] The detail field's shown/hidden state is client-side only (no page reload) and defaults to hidden on page load.
- [ ] Form shows a required `description` textarea.
- [ ] This task does not implement submit/validation — that's #10. If the browser is not JS-capable, the detail field degrades to always-visible (progressive enhancement), so no submission path is silently broken.

## Out of scope

- Server-side validation that `category_other_detail` is filled in when "Other" is chosen — part of #10's save logic.

## Constraints

- Extends the same template/view introduced in #5; no new page.

**Comment by musaalamparvez** [comment]
Merged into #5 as part of MVP task consolidation — this and #7, #8, #9 were all fields on the same single form/view, too fine-grained to track separately. Closing.
